site:
  name: "Blulu Metrics: A Rethink Of The Relationship Between Web Tools And Deliberative Democracy"
  name_tw: Blulu 量表：重新思考網路工具與審議民主的關係
  url: "https://etblue.github.io/blulu"
  image: "images/cover.png"
project:
  name: "Blulu Metrics"
  name_tw: "Blulu 量表"
  tagline: A Rethink Of The Relationship Between Web Tools And Deliberative Democracy
  tagline_tw: 重新思考網路工具與審議民主的關係
  description: "Blulu is a framework describing the emerging relationship between public deliberation, participatory democracy and information technology. Named after last names of its co-authors: Chia-Hua Lü and ETBlue." 
  description_tw: "Blulu 是一組思考框架，用以分析公共審議、參與式民主與資訊科技之間的新興關係。以兩位共同作者呂家華、藍一婷的姓氏來命名。"
  why: Since the Sunflower Movement in 2014, digital democracy became a rising star in Taiwan. The Taiwan Authority imported a bunch of trendy online and offline participatory tools, as well as a couple of techies from the civil tech community. Yet, in no time, tools-based open washing emerged. To point out the dark side and call for public awareness of open washing, the Blulu Metrics was developed.
  why_tw: 自 2014 佔領立院後，數位民主風潮興起，台灣治理當局引進了許多新潮的線上與線下的參與工具，同時從公民科技社群網羅技術人才。但很快地，基於工具的洗白式開放隨之出現。為了指出暗面、激起大眾對洗白式開放的警覺，Blulu 量表就此誕生。
  logo:
  cover:
  content:
    - onion
    - train
    - stair
    - iceberg
    - pizza
    - meter
    - spectrum
    - bricks
author:
  - name: "Chia-Hua Lü"
    name_tw: "呂家華"
    tagline: An experienced facilitator, planner, mediator, researcher and consultant diving into the professional field of public deliberation for more than ten years.
    tagline_tw: 經驗深厚的審議主持人、規劃師、中介者、研究人員、以及顧問，在公共審議的領域中深耕十餘載的專業工作者。
    description: 
    description_tw:
    avatar:
    link:
      - icon: "twitter"
        color: "twitter"
        title: "ChiA huA"
        url: "https://twitter.com/chiahua0515"
      - icon: "facebook f"
        color: "facebook"
        title: "Lu Chia Hua"
        url: "https://www.facebook.com/luchiahua0515"
  - name: "ETBlue"
    name_tw: "藍一婷"
    tagline: A medical illustrator, business planner, web UI designer, web frontend engineer, singer-songwriter and open source contributor participated in g0v.tw community.
    tagline_tw: 醫學繪圖插畫家、商務企畫員、網站介面設計人、網頁前端工程師、創作歌手，參與台灣零時政府社群的開源貢獻者。
    description:
    description_tw:
    avatar:
    link:
      - icon: "twitter"
        color: "twitter"
        title: "ETBlue"
        url: "https://twitter.com/ETBlue"
      - icon: "facebook f"
        color: "facebook"
        title: "ETBlue"
        url: "https://www.facebook.com/ETBlue"
artist:
  - name: "Tuiry Hsiao"
    name_tw: "蕭煦平"
    tagline: A super talented illustrator creating adorable characters and paintings just like magic. An open art contributor participated in g0v.tw community.
    tagline_tw: 像是變魔術般創作出可愛角色與主視覺插圖的天才畫家，同時也是參與台灣零時政府社群的開放藝術貢獻者。
    link:
      - icon: "facebook f"
        color: "facebook"
        title: "Tuiry Hsiao"
        url: "https://www.facebook.com/tuiry.hsiao"
brainstormer:
  - name: "Peggy Lo"
    name_tw: "羅佩琪"
    tagline: A planner, facilitator, listener, communicator and mediator with blessed high EQ and a warm heart. An experienced worker in government and non-government as well as an open source contributor participated in g0v.tw community.
    tagline_tw: 規劃師、主持人、中介者、聆聽者、溝通家，擁有受到祝福的高 EQ 及溫暖的心房。經驗豐富的政府及非政府工作人，同時也是參與台灣零時政府社群的開源專案貢獻者。
    link:
      - icon: "facebook f"
        color: "facebook"
        title: "Pei-Chi Lo"
        url: "https://www.facebook.com/peichi.lo.3"
  - name: "Ming-Han Tsai"
    name_tw: "蔡明翰"
    tagline: An observer, storyteller, activist, mediator with unlimited punch lines. An experienced public servant worked in both local and central government, as well as an open source contributor participated in g0v.tw community.
    tagline_tw: 觀察者、說書人、行動家、中介者，擁有用不完的的搞笑梗。在中央及地方政府任職，是經驗豐富的公務員，同時也是參與台灣零時政府社群的開源專案貢獻者。
    link:
      - icon: "facebook f"
        color: "facebook"
        title: "Ming-Han Tsai"
        url: "https://www.facebook.com/minghan.tsai1"
thank:
  - name: "Loomio"
    name_tw: "Loomio"
    url: "https://www.loomio.org/"
  - name: "Open Culture Foundation"
    name_tw: "開放文化基金會"
    url: "http://ocf.tw/"
  - name: "Taiwan Civil Service Innovation Coalition"
    name_tw: "台灣公務革新力量聯盟"
    url: "https://www.facebook.com/thinking4public/"
  - name: "Whiski Tajfun"
    name_tw: "張維志"
    url: "https://www.facebook.com/TajfunInsulo"

speech:
  - name: Blulu Alpha Version - Part 1
    name_tw: Blulu Alpha 版：上半場
    description: Alpha version was published at the end of 2015 in an event held for the Loomio team, hosted by Open Culture Foundation. The first part focused on describing the nature of public deliberation.
    description_tw: Alpha 版本於 2015 年底一場開放文化基金會為了 Loomio 團隊來台而舉辦的活動中發佈，上半場主要描述公共審議的本質。
    toc:
      - title: What does Blulu do
        title_tw: Blulu 的功能與用途
      - title: Me as a mediator
        title_tw: 身為中介者的視角
      - title: The role of online tools
        title_tw: 線上工具扮演的角色
      - title: Composition of deliberation versus process of a deliberation event
        title_tw: 審議的組成與操作流程
      - title: Composition 1. Presentation of information
        title_tw: 審議組成一：資訊呈現
      - title: Composition 2. Tools, modes and patterns
        title_tw: 審議組成二：技巧、工具、與進行模式
      - title: Composition 2-1. Different modes versus different stages of public policy life cycle
        title_tw: 審議組成二之一：不同模式在不同政策生命週期中的應用
      - title: Composition 2-2. Different modes versus different stages of public deliberation event
        title_tw: 審議組成二之二：不同模式在不同審議活動進行階段中的應用
      - title: Composition 3. Facilitation
        title_tw: 審議組成三：主持討論
      - title: Composition 4. Choices in different politic contexts
        title_tw: 在不同政治脈絡下做選擇
      - title: Three groups related to a public policy making
        title_tw: 公共政策的三組關係人
    link:
      - title: Online collaborative document
        title_tw: 線上協作共筆
        url: https://ocf-tw.hackpad.com/Loomio-l8fikCsKHiG
        language:
          - Zh
          - En
      - title: Some thoughts from the speaker
        title_tw: 講者感言
        url: https://www.facebook.com/luchiahua0515/posts/10153441102061026
        language:
          - Zh
    slides_language:
      - Zh
    video_language:
      - Zh
    slides: '<div style="position:relative;height:0;padding-bottom:56.25%;"><iframe src="//www.slideshare.net/slideshow/embed_code/key/fzt8L0JkJAk8Qd" width="595" height="485" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="position:absolute;width:100%;height:100%;left:0;border:none;" allowfullscreen> </iframe></div><p class="center aligned"><strong><a href="//www.slideshare.net/luchiahua0515/20151209-blulu-part-1-deliberate-concept-web-applications-x-public-deliberation" title="20151209 Blulu - Part 1 : Deliberate Concept |Web Applications x Public Deliberation" target="_blank">20151209 Blulu - Part 1 : Deliberate Concept |Web Applications x Public Deliberation</a></strong> from <strong><a target="_blank" href="https://www.slideshare.net/chiahua">chiahua</a></strong></p>'
    video: '<div style="position:relative;height:0;padding-bottom:56.25%"><iframe src="https://www.youtube.com/embed/ljYsnbSOK7I?ecver=2" width="640" height="360" frameborder="0" style="position:absolute;width:100%;height:100%;left:0" allowfullscreen></iframe></div>'
  - name: Blulu Alpha Version - Part 2
    name_tw: Blulu Alpha 版：下半場
    description: The position of online tools was well explained in the second part, taking two similiar cases on the Loomio platform as examples for comparison.
    description_tw: 下半場以 Loomio 平台上兩件相似的案例做比較，解釋線上工具在公共審議中的定位。
    toc:
      - title: Where Could Web Apps Help Us in Deliberation
        title_tw: 網路工具可以應用在審議的哪裡
      - title: Goals, Needs and Tools of Each Step of Deliberation
        title_tw: 每個審議步驟的目標、需求與適用工具
      - title: Where are Loomio and Their Cases in Blulu Concept
        title_tw: Loomio 與相關案例的定位
      - title: Some Thoughts
        title_tw: 個人觀察
    link:
      - title: Online collaborative document
        title_tw: 線上協作共筆
        url: https://ocf-tw.hackpad.com/Loomio-l8fikCsKHiG
        language:
          - Zh
          - En
      - title: Some thoughts from the speaker
        title_tw: 講者感言
        url: https://www.facebook.com/ETBlue/posts/10206010200586796
        language:
          - Zh
      - title: Blog post
        title_tw: 部落格文章
        url: https://etblue.blogspot.tw/2015/12/loomio-20-blulu.html
        language:
          - Zh
    slides_language:
      - Zh
      - En
    video_language:
      - Zh
    slides: '<div style="position:relative;height:0;padding-bottom:56.25%"><iframe src="https://docs.google.com/presentation/d/19GFnA_ecKmJRcNNrluilIEVByXmY4YAfOXYQmzwmJWY/embed?start=false&loop=false&delayms=3000" frameborder="0" width="640" height="360" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true" frameborder="0" style="position:absolute;width:100%;height:100%;left:0"></iframe></div>'
    video: '<div style="position:relative;height:0;padding-bottom:56.25%"><iframe src="https://www.youtube.com/embed/EmvNTjZWaos?ecver=2" width="640" height="360" frameborder="0" style="position:absolute;width:100%;height:100%;left:0" allowfullscreen></iframe></div>'
  - name: Blulu Beta Version
    name_tw: Blulu Beta 版
    description: Beta version was published in the middle of 2016 in G0V Summit, pointing out the outer and inner side of civic engagement for public policies.
    description_tw: Beta 版本於 2016 年中的零時政府峰會中發佈，指出公民參與政策制定的表面與裏面。
    toc:
      - title: Who I am
        title_tw: 自我介紹
      - title: Adorable paintings from Tuiry Hsiao
        title_tw: 阿平老師的可愛繪圖
      - title: What does Blulu do
        title_tw: Blulu 的用途
      - title: Me as a mediator
        title_tw: 身為中介者的視角
      - title: Inner side, outer side, one-off and on-going pattern of deliberation in politics
        title_tw: 審議在政治脈絡下的表與裏、炒作與永續
      - title: History and trends of deliberation in Taiwan
        title_tw: 台灣近年審議發展的歷史與趨勢
      - title: Inner and outer of public policy life cycle
        title_tw: 公共政策生命週期的表與裏
      - title: Inner and outer of deliberation process
        title_tw: 審議進行流程的表與裏
      - title: Inner and outer of deliberation composition
        title_tw: 審議組成本質的表與裏
      - title: Examples
        title_tw: 案例分析
      - title: "Call to action: project planning hackathon for NGO"
        title_tw: 採取行動：NGO 企畫松
      - title: The roles of g0v hackathon and NGO planning hackathon
        title_tw: NGO 企畫松與 g0v 黑客松的定位
    link:
      - title: Online collaborative document
        title_tw: 線上協作共筆
        url: https://g0v.hackpad.com/R0-Square-g0v-Summit-2016-2ldPbEHoVJ0#:h=政府-x-民間-x-網路-x-審議-一個中介者的觀察與思考-
        language:
          - Zh
    slides_language:
      - Zh
    video_language:
      - Zh
    slides: '<div style="position:relative;height:0;padding-bottom:56.25%;"><iframe src="//www.slideshare.net/slideshow/embed_code/key/2EheV459PPWVAm" width="595" height="485" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="position:absolute;width:100%;height:100%;left:0;border:none;" allowfullscreen> </iframe></div><p class="center aligned"><strong><a href="//www.slideshare.net/chiahua/x-x-x-62023806" title="政府 x 民間 x 網路 x 審議 一個中介者的觀察與思考" target="_blank">政府 x 民間 x 網路 x 審議 一個中介者的觀察與思考</a></strong> from <strong><a target="_blank" href="https://www.slideshare.net/chiahua">chiahua</a></strong></p>'
    video: '<div style="position:relative;height:0;padding-bottom:56.25%"><iframe src="https://www.youtube.com/embed/RJsvuh5-Djw?ecver=2" width="640" height="360" frameborder="0" style="position:absolute;width:100%;height:100%;left:0" allowfullscreen></iframe></div>'
  - name: Blulu Gamma Version
    name_tw: Blulu Gamma 版
    description: Gamma version is coming at 5/13 2017, providing thinking tools for open washing disclosure.
    description_tw: Gamma 版本即將在 2017/5/13 發佈，提供辨別開放式洗白的思考工具。
    toc:
      - title: "Which Force To Join: Technology Neutrality Under A Political Competition"
        title_tw: 跳坑指南：政治賽局下的技術中立
      - title: "How To Cowork: Halo Effect Across Domains"
        title_tw: 挖坑指南：跨領域下的光暈效應
      - title: "What To Observe: Open V.S. Open Washed"
        title_tw: 觀坑指南：開放透明的表與裏
      - title: Some Thoughts As An Ordinary Citizen
        title_tw: 結語：身為普通公民
    slides_language:
      - Zh
      - En
    video_language:
      - Zh
    slides: <p class="center aligned">To Be Published</p>
    video: <p class="center aligned">To Be Published</p>

painting:
  - images/blulu-rushing.jpg
  - images/blulu-teal-circle.png
  - images/blulu-yellow-circle.png
  - images/blulu-white-board.png
  - images/blulu-fuck-world-cafe.png
  - images/blulu-handsome.png

music:
  link:
      - title: Behind the scenes
        title_tw: 幕後花絮
        url: https://etblue.blogspot.tw/2017/04/blulu-gamma.html
        language:
          - Zh
