site:
  name: "Blulu Metrics: A Rethink of the Relationship Between Web Tools and Deliberative Democracy"
  name_tw: Blulu 量表：重新思考網路工具與審議民主的關係
  url: "http://blulu.tw"
  cover: "/images/cover.png"
  icon: "/images/favicon.png"
project:
  name: "Blulu Metrics"
  name_tw: "Blulu 量表"
  tagline: A Rethink of the Relationship Between Web Tools and Deliberative Democracy
  tagline_tw: 重新思考網路工具與審議民主的關係
  description: "Blulu is a framework describing the emerging relationship between deliberation, participation and information technology. Named after last names of its co-authors: Chia-Hua Lü and ETBlue." 
  description_tw: "Blulu 是一組思考框架，用以分析審議、參與與資訊科技之間的新興關係。以兩位共同作者呂家華、藍一婷的姓氏來命名。"
  why: Since the Sunflower Movement in 2014, digital democracy became a rising star in Taiwan. The Taiwan Authority imported bunch of trendy online and offline participatory tools, as well as a couple of techies from the civil tech community. Yet, in no time, tools-based open washing emerged. To point out the dark side and call for public awareness of open washing, the Blulu Metrics was developed.
  why_tw: 自 2014 佔領立院後，數位民主風潮興起，台灣治理當局引進了許多新潮的線上與線下的參與工具，同時從公民科技社群網羅技術人才。但很快地，基於工具的洗白式開放隨之出現。為了指出暗面、激起大眾對洗白式開放的警覺，Blulu 量表就此誕生。
  logo:
  cover:
  content:
    - onion
    - train
    - stair
    - iceberg
    - pizza
    - meter
    - spectrum
    - bricks
author:
  - name: "Chia-Hua Lü"
    name_tw: "呂家華"
    tagline: An experienced facilitator, planner, mediator, researcher and consultant diving the professional fiion public deliberation for more than ten years.
    tagline_tw: 經驗深厚的審議主持人、規劃師、中介者、研究人員、以及顧問，在審議的領域十餘載的專業工作者。
    description: 
    description_tw:
    avatar:
    link:
      - icon: "twitter"
        color: "twitter"
        title: "ChiA huA"
        url: "https://twitter.com/chiahua0515"
      - icon: "facebook f"
        color: "facebook"
        title: "Lu Chia Hua"
        url: "https://www.facebook.com/luchiahua0515"
  - name: "ETBlue"
    name_tw: "藍一婷"
    tagline: A medical illustrator, business planner, web UI designer, web frontend engineer, singer songwriter and open source contributor participated in g0v.tw community.
    tagline_tw: 醫學繪圖插畫家、商務企畫員、網站介面設計人、網頁前端工程師、創作歌手，參與台灣零時政府社群的開源貢獻者。
    description:
    description_tw:
    avatar:
    link:
      - icon: "twitter"
        color: "twitter"
        title: "ETBlue"
        url: "https://twitter.com/ETBlue"
      - icon: "facebook f"
        color: "facebook"
        title: "ETBlue"
        url: "https://www.facebook.com/ETBlue"
artist:
  - name: "Tuiry Hsiao"
    name_tw: "蕭煦平"
    tagline: A super talented illustrator creating adorable characters and paintings just like magic. An open art contributor participated in g0v.tw community.
    tagline_tw: 像是變魔術般創作出可愛角色與主視覺插圖的天才畫家，同時也是參與台灣零時政府社群的開放藝術貢獻者。
    link:
      - icon: "twitter"
        color: "twitter"
        title: "tuiry //:..:"
        url: "https://twitter.com/tu_hsiao"
      - icon: "facebook f"
        color: "facebook"
        title: "Tuiry Hsiao"
        url: "https://www.facebook.com/tuiry.hsiao"
brainstormer:
  - name: "Peggy Lo"
    name_tw: "羅佩琪"
    tagline: A planner, bridge-builder, listener and communicator with blessed high EQ and a warm heart. An experienced worker in government and non-government as well as an open source contributor participated in g0v.tw community.
    tagline_tw: 規劃師、搭橋者、聆聽者、溝通家，擁有受到祝福的高 EQ 及溫暖的心房。經驗豐富的政府及非政府工作人，同時也是參與台灣零時政府社群的開源專案貢獻者。
    link:
      - icon: "facebook f"
        color: "facebook"
        title: "Pei-Chi Lo"
        url: "https://www.facebook.com/peichi.lo.3"
  - name: "Ming-Han Tsai"
    name_tw: "蔡明翰"
    tagline: An observer, storyteller, activist, mediator with unlimited punch lines. An experienced public servant worked in both local and central government, as well as an open source contributor participated in g0v.tw community.
    tagline_tw: 觀察者、說書人、行動家、中介者，擁有用不完的搞笑梗。在中央及地方政府任職，是經驗豐富的公務員，同時也是參與台灣零時政府社群的開源專案貢獻者。
    link:
      - icon: "facebook f"
        color: "facebook"
        title: "Ming-Han Tsai"
        url: "https://www.facebook.com/minghan.tsai1"
thank:
  - name: "Loomio"
    name_tw: "Loomio"
    url: "https://www.loomio.org/"
  - name: "Open Culture Foundation"
    name_tw: "開放文化基金會"
    url: "http://ocf.tw/"
  - name: "Taiwan Civil Service Innovation Coalition"
    name_tw: "台灣公務革新力量聯盟"
    url: "https://www.facebook.com/thinking4public/"
  - name: "Whiski Tajfun"
    name_tw: "張維志"
    url: "https://www.facebook.com/TajfunInsulo"

speech:
  - name: Blulu Alpha Version - Part 1
    name_tw: Blulu Alpha 版：上半場
    description: Alpha version was published at the end of 2015 in an event held for the Loomio team, hosted by Open Culture Foundation. The first part focused on describing the nature of public deliberation.
    description_tw: Alpha 版本於 2015 年底一場開放文化基金會為了 Loomio 團隊來台而舉辦的活動中發佈，上半場主要描述公共審議的本質。
    title: "Web Applications x Public Deliberation"
    title_tw: 網路應用 x 公共審議
    subtitle: "Part 1 : Deliberation Concept"
    subtitle_tw: 上半場：審議概念篇
    slides_language:
      - Zh
    video_language:
      - Zh
    slides: '<iframe src="//www.slideshare.net/slideshow/embed_code/key/fzt8L0JkJAk8Qd" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="position:absolute;width:100%;height:100%;left:0;border:none;" allowfullscreen> </iframe>'
    video: '<iframe id="video_alpha1" enablejsapi="true" src="https://www.youtube.com/embed/ljYsnbSOK7I?enablejsapi=1" frameborder="0" style="position:absolute;width:100%;height:100%;left:0" allowfullscreen></iframe>'
    toc_id: alpha1
    meta:
      - title: December 09, 2015
        title_tw: 2015 年 12 月 9 日
        label: Date
        label_tw: 日期
      - title: Appier Cafe, Taipei, Taiwan
        title_tw: 台灣國台北市，Appier Cafe
        label: Location
        label_tw: 地點
        url: "https://www.appier.com"
      - title: Open Culture Foundation (International Exchange)
        title_tw: 開放文化基金會（國際交流）
        label: Host
        label_tw: 主辦
        url: "http://ocf.tw/"
      - title: Loomio, Deliberation, Don-Democracy
        title_tw: Loomio、審議、動民主
        label: Event
        label_tw: 活動
        url: "https://ocftw.kktix.cc/events/blulu"
      - title: Chia-Hua Lü
        title_tw: 呂家華
        label: Speaker
        label_tw: 講者
    toc:
      - title: Topics for this session
        title_tw: 本場內容
        timestamp: 1:01
        label: "1:01"
      - title: Who I am
        title_tw: 自我介紹
        timestamp: 2:14
        label: "2:14"
      - title: My point of view as a mediator
        title_tw: 身為中介者的視角
        timestamp: 3:53
        label: "3:53"
      - title: The role of online tools
        title_tw: 線上工具扮演的角色
        timestamp: 4:50
        label: "4:50"
      - title: Composition of deliberation versus process of a deliberation event
        title_tw: 審議的組成與操作流程
        timestamp: 5:44
        label: "5:44"
      - title: Composition 1. Presentation of information
        title_tw: 審議組成一：資訊呈現
        timestamp: 8:22
        label: "8:22"
      - title: Composition 2. Tools, modes and patterns
        title_tw: 審議組成二：技巧、工具、與進行模式
        timestamp: 12:20
        label: "12:20"
      - title: Composition 2-1. Different modes versus different stages of public policy life cycle
        title_tw: 審議組成二之一：不同模式在不同政策生命週期中的應用
        timestamp: 13:53
        label: "13:53"
      - title: Composition 2-2. Different modes versus different stages of public deliberation event
        title_tw: 審議組成二之二：不同模式在不同審議活動進行階段中的應用
        timestamp: 20:06
        label: "20:06"
      - title: Composition 3. Facilitation
        title_tw: 審議組成三：主持討論
        timestamp: 22:01
        label: "22:01"
      - title: Composition 4. Choices in different politic contexts
        title_tw: 在不同政治脈絡下做選擇
        timestamp: 22:46
        label: "22:46"
      - title: Three groups related to a public policy making
        title_tw: 公共政策的三組關係人
        timestamp: 23:25
        label: "23:25"
    link:
      - title: Online collaborative document
        title_tw: 線上協作共筆
        url: https://ocf-tw.hackpad.com/Loomio-l8fikCsKHiG
        language:
          - Zh
          - En
      - title: Some thoughts from the speaker
        title_tw: 講者感言
        url: https://www.facebook.com/luchiahua0515/posts/10153441102061026
        language:
          - Zh
  - name: Blulu Alpha Version - Part 2
    name_tw: Blulu Alpha 版：下半場
    description: The position of online tools was well explained in the second part, taking two similiar cases on the Loomio platform as examples for comparison.
    description_tw: 下半場以 Loomio 平台上兩件相似的案例做比較，解釋線上工具在公共審議中的定位。
    title: "Web Applications x Public Deliberation"
    title_tw: 網路應用 x 公共審議
    subtitle: "Part 2 : Web Applications"
    subtitle_tw: 下半場：網路工具篇
    slides_language:
      - Zh
      - En
    video_language:
      - Zh
    slides: '<iframe src="https://docs.google.com/presentation/d/19GFnA_ecKmJRcNNrluilIEVByXmY4YAfOXYQmzwmJWY/embed?start=false&loop=false&delayms=3000" frameborder="0" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true" frameborder="0" style="position:absolute;width:100%;height:100%;left:0"></iframe>'
    video: '<iframe id="video_alpha2" enablejsapi="true" src="https://www.youtube.com/embed/EmvNTjZWaos?enablejsapi=1" frameborder="0" style="position:absolute;width:100%;height:100%;left:0" allowfullscreen></iframe>'
    toc_id: alpha2
    meta:
      - title: ETBlue
        title_tw: 藍一婷
        label: Speaker
        label_tw: 講者
    toc:
      - title: Who I am
        title_tw: 自我介紹
        timestamp: 0:52
        label: "52"
      - title: Where could web apps help us in deliberation
        title_tw: 網路工具可以應用在審議的哪裡
        timestamp: 1:22
        label: "1:22"
      - title: Goals, needs and tools of each step of deliberation
        title_tw: 每個審議步驟的目標、需求與適用工具
        timestamp: 4:50
        label: "4:50"
      - title: Where are loomio and their cases in blulu concept
        title_tw: Loomio 與相關案例的定位
        timestamp: 8:03
        label: "8:03"
      - title: Some thoughts
        title_tw: 個人觀察
        timestamp: 13:20
        label: "13:20"
    link:
      - title: Online collaborative document
        title_tw: 線上協作共筆
        url: https://ocf-tw.hackpad.com/Loomio-l8fikCsKHiG
        language:
          - Zh
          - En
      - title: Some thoughts from the speaker
        title_tw: 講者感言
        url: https://www.facebook.com/ETBlue/posts/10206010200586796
        language:
          - Zh
      - title: Blog post
        title_tw: 部落格文章
        url: https://etblue.blogspot.tw/2015/12/loomio-20-blulu.html
        language:
          - Zh
  - name: Blulu Beta Version
    name_tw: Blulu Beta 版
    description: Beta version was published in the middle of 2016 in G0V Summit, pointing out the outer and inner side of civic engagement for public policies.
    description_tw: Beta 版本於 2016 年中的零時政府峰會中發佈，指出公民參與政策制定的表面與裏面。
    title: "Government x Civil Society x Internet x Deliberation"
    title_tw: 政府 x 民間 x 網路 x 審議
    subtitle: "Observations and Reflections of a Mediator"
    subtitle_tw: 一個中介者的觀察與思考
    slides_language:
      - Zh
    video_language:
      - Zh
    slides: '<iframe src="//www.slideshare.net/slideshow/embed_code/key/2EheV459PPWVAm" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="position:absolute;width:100%;height:100%;left:0;border:none;" allowfullscreen> </iframe>'
    video: '<iframe id="video_beta" enablejsapi="true" src="https://www.youtube.com/embed/esBQ0OIu-cw?enablejsapi=1" frameborder="0" style="position:absolute;width:100%;height:100%;left:0" allowfullscreen></iframe>'
    toc_id: beta
    meta:
      - title: May 15, 2016
        title_tw: 2016 年 5 月 15 日
        label: Date
        label_tw: 日期
      - title: Academia Sinica, Taiper, Taiwan
        title_tw: 台灣國台北市，中央研究院
        label: Location
        label_tw: 地點
      - title: G0V Summit 2016
        title_tw: 2016 零時政府峰會
        label: Host
        label_tw: 主辦
        url: "http://summit.g0v.tw/2016/"
      - title: Chia-Hua Lü
        title_tw: 呂家華
        label: Speaker
        label_tw: 講者
    toc:
      - title: Who I am + adorable paintings from Tuiry Hsiao
        title_tw: 自我介紹 + 阿平老師的可愛繪圖
        timestamp: 1:00
        label: "1:00"
      - title: Topics for this session
        title_tw: 本場內容
        timestamp: 2:34
        label: "2:34"
      - title: My points of view as a mediator
        title_tw: 身為中介者的視角
        timestamp: 3:13
        label: "3:13"
      - title: History and trends of deliberation in Taiwan
        title_tw: 台灣近年審議發展的歷史與趨勢
        timestamp: 4:42
        label: "4:42"
      - title: The concept of inners and outers
        title_tw: 表與裏的概念
        timestamp: 11:41
        label: "11:41"
      - title: Inners and outers of public policy life cycle
        title_tw: 公共政策生命週期的表與裏
        timestamp: 13:09
        label: "13:09"
      - title: Inners and outers of deliberation process
        title_tw: 審議進行流程的表與裏
        timestamp: 15:38
        label: "15:38"
      - title: Inners and outers of deliberation composition
        title_tw: 審議組成本質的表與裏
        timestamp: 23:09
        label: "23:09"
      - title: Different situations in government and non-government
        title_tw: 政府與民間的狀態差異
        timestamp: 23:42
        label: "23:42"
      - title: "Call to action: project planning hackathon for NGO"
        title_tw: 採取行動：NGO 企畫松
        timestamp: 26:38
        label: "26:38"
      - title: Questions and answers
        title_tw: 問與答
        timestamp: 28:40
        label: "28:40"
    link:
      - title: Online collaborative document
        title_tw: 線上協作共筆
        url: https://g0v.hackpad.com/R0-Square-g0v-Summit-2016-2ldPbEHoVJ0#:h=政府-x-民間-x-網路-x-審議-一個中介者的觀察與思考-
        language:
          - Zh
  - name: Blulu Gamma Version
    name_tw: Blulu Gamma 版
    description: Gamma version is coming at 5/13 2017, providing thinking tools for open washing disclosure.
    description_tw: Gamma 版本即將在 2017/5/13 發佈，提供辨別洗白式開放的思考工具。
    slides_language:
      - Zh
      - En
    video_language:
      - Zh
    slides: <p class="center aligned">To Be Published</p>
    video: <p class="center aligned">To Be Published</p>
    toc_id: gamma
    meta:
    toc:
      - title: "Which force to join: technology neutrality under a political competition"
        title_tw: 跳坑指南：政治賽局下的技術中立
        timestamp: 
        label: 
      - title: "How to cowork: halo effect across domains"
        title_tw: 挖坑指南：跨領域下的光暈效應
        timestamp: 
        label: 
      - title: "What to observe: open v.s. open washed"
        title_tw: 觀坑指南：開放透明的表與裏
        timestamp: 
        label: 
      - title: Some thoughts as an ordinary citizen
        title_tw: 結語：身為普通公民
        timestamp: 
        label: 
    link:

painting:
  - images/blulu-rushing.jpg
  - images/blulu-teal-circle.png
  - images/blulu-yellow-circle.png
  - images/blulu-white-board.png
  - images/blulu-fuck-world-cafe.png
  - images/blulu-handsome.png

music:
  link:
      - title: Behind the scenes
        title_tw: 幕後花絮
        url: https://etblue.blogspot.tw/2017/04/blulu-gamma.html
        language:
          - Zh
