name: Blulu’s Train
name_tw: Blulu 列車
nick: Deliberation procedures
nick_tw: 審議的步驟
tagline: Process of public deliberation
tagline_tw: 公共審議的流程
description: 
description_tw:
avatar: "images/metrics-train.png"
cover:
